### ISSUE TITLE
init-présentation

### ISSUE THREAD

**Issue by essarraj-fouad** [labs-web/lab-composer#12]
# Travail à faire
- Élaboration d'un présentation sans contenu avec les pages et leurs titres
- ajouter le lien du présentation dans index.md
# Livrable
- docs/*
- backlog/sous-tache/1.init-présentation.98.md
- README.json
- README.md

**Comment by essarraj-fouad** [comment]
- L'issue n'est pas liée avec une pull request ouverte

**Comment by zaani12** [comment]
- Il faut respecter l'ordre des tâches 
    - la tache a realiser : init-rapport
